<option value="af" <?php if($CurrentSetting == "af") print " selected "; ?>>Afghanistan (AF)</option>
<option value="ax" <?php if($CurrentSetting == "ax") print " selected "; ?>>Åland Islands (AX)</option>
<option value="al" <?php if($CurrentSetting == "al") print " selected "; ?>>Albania (AL)</option>
<option value="dz" <?php if($CurrentSetting == "dz") print " selected "; ?>>Algeria (DZ)</option>
<option value="as" <?php if($CurrentSetting == "as") print " selected "; ?>>American Samoa (AS)</option>
<option value="ad" <?php if($CurrentSetting == "ad") print " selected "; ?>>Andorra (AD)</option>
<option value="ao" <?php if($CurrentSetting == "ao") print " selected "; ?>>Angola (AO)</option>
<option value="ai" <?php if($CurrentSetting == "ai") print " selected "; ?>>Anguilla (AI)</option>
<option value="aq" <?php if($CurrentSetting == "aq") print " selected "; ?>>Antarctica (AQ)</option>
<option value="ag" <?php if($CurrentSetting == "ag") print " selected "; ?>>Antigua And Barbuda (AG)</option>
<option value="ar" <?php if($CurrentSetting == "ar") print " selected "; ?>>Argentina (AR)</option>
<option value="am" <?php if($CurrentSetting == "am") print " selected "; ?>>Armenia (AM)</option>
<option value="aw" <?php if($CurrentSetting == "aw") print " selected "; ?>>Aruba (AW)</option>
<option value="au" <?php if($CurrentSetting == "au") print " selected "; ?>>Australia (AU)</option>
<option value="at" <?php if($CurrentSetting == "at") print " selected "; ?>>Austria (AT)</option>
<option value="az" <?php if($CurrentSetting == "az") print " selected "; ?>>Azerbaijan (AZ)</option>
<option value="bs" <?php if($CurrentSetting == "bs") print " selected "; ?>>Bahamas (BS)</option>
<option value="bh" <?php if($CurrentSetting == "bh") print " selected "; ?>>Bahrain (BH)</option>
<option value="bd" <?php if($CurrentSetting == "bd") print " selected "; ?>>Bangladesh (BD)</option>
<option value="bb" <?php if($CurrentSetting == "bb") print " selected "; ?>>Barbados (BB)</option>
<option value="by" <?php if($CurrentSetting == "by") print " selected "; ?>>Belarus (BY)</option>
<option value="be" <?php if($CurrentSetting == "be") print " selected "; ?>>Belgium (BE)</option>
<option value="bz" <?php if($CurrentSetting == "bz") print " selected "; ?>>Belize (BZ)</option>
<option value="bj" <?php if($CurrentSetting == "bj") print " selected "; ?>>Benin (BJ)</option>
<option value="bm" <?php if($CurrentSetting == "bm") print " selected "; ?>>Bermuda (BM)</option>
<option value="bt" <?php if($CurrentSetting == "bt") print " selected "; ?>>Bhutan (BT)</option>
<option value="bo" <?php if($CurrentSetting == "bo") print " selected "; ?>>Bolivia, Plurinational State Of (BO)</option>
<option value="bq" <?php if($CurrentSetting == "bq") print " selected "; ?>>Bonaire, Sint Eustatius And Saba (BQ)</option>
<option value="ba" <?php if($CurrentSetting == "ba") print " selected "; ?>>Bosnia And Herzegovina (BA)</option>
<option value="bw" <?php if($CurrentSetting == "bw") print " selected "; ?>>Botswana (BW)</option>
<option value="bv" <?php if($CurrentSetting == "bv") print " selected "; ?>>Bouvet Island (BV)</option>
<option value="br" <?php if($CurrentSetting == "br") print " selected "; ?>>Brazil (BR)</option>
<option value="io" <?php if($CurrentSetting == "io") print " selected "; ?>>British Indian Ocean Territory (IO)</option>
<option value="bn" <?php if($CurrentSetting == "bn") print " selected "; ?>>Brunei Darussalam (BN)</option>
<option value="bg" <?php if($CurrentSetting == "bg") print " selected "; ?>>Bulgaria (BG)</option>
<option value="bf" <?php if($CurrentSetting == "bf") print " selected "; ?>>Burkina Faso (BF)</option>
<option value="bi" <?php if($CurrentSetting == "bi") print " selected "; ?>>Burundi (BI)</option>
<option value="kh" <?php if($CurrentSetting == "kh") print " selected "; ?>>Cambodia (KH)</option>
<option value="cm" <?php if($CurrentSetting == "cm") print " selected "; ?>>Cameroon (CM)</option>
<option value="ca" <?php if($CurrentSetting == "ca") print " selected "; ?>>Canada (CA)</option>
<option value="cv" <?php if($CurrentSetting == "cv") print " selected "; ?>>Cape Verde (CV)</option>
<option value="ky" <?php if($CurrentSetting == "ky") print " selected "; ?>>Cayman Islands (KY)</option>
<option value="cf" <?php if($CurrentSetting == "cf") print " selected "; ?>>Central African Republic (CF)</option>
<option value="td" <?php if($CurrentSetting == "td") print " selected "; ?>>Chad (TD)</option>
<option value="cl" <?php if($CurrentSetting == "cl") print " selected "; ?>>Chile (CL)</option>
<option value="cn" <?php if($CurrentSetting == "cn") print " selected "; ?>>China (CN)</option>
<option value="cx" <?php if($CurrentSetting == "cx") print " selected "; ?>>Christmas Island (CX)</option>
<option value="cc" <?php if($CurrentSetting == "cc") print " selected "; ?>>Cocos (keeling) Islands (CC)</option>
<option value="co" <?php if($CurrentSetting == "co") print " selected "; ?>>Colombia (CO)</option>
<option value="km" <?php if($CurrentSetting == "km") print " selected "; ?>>Comoros (KM)</option>
<option value="cg" <?php if($CurrentSetting == "cg") print " selected "; ?>>Congo (CG)</option>
<option value="cd" <?php if($CurrentSetting == "cd") print " selected "; ?>>Congo, The Democratic Republic Of The (CD)</option>
<option value="ck" <?php if($CurrentSetting == "ck") print " selected "; ?>>Cook Islands (CK)</option>
<option value="cr" <?php if($CurrentSetting == "cr") print " selected "; ?>>Costa Rica (CR)</option>
<option value="ci" <?php if($CurrentSetting == "ci") print " selected "; ?>>Côte D'ivoire (CI)</option>
<option value="hr" <?php if($CurrentSetting == "hr") print " selected "; ?>>Croatia (HR)</option>
<option value="cu" <?php if($CurrentSetting == "cu") print " selected "; ?>>Cuba (CU)</option>
<option value="cw" <?php if($CurrentSetting == "cw") print " selected "; ?>>Curaçao (CW)</option>
<option value="cy" <?php if($CurrentSetting == "cy") print " selected "; ?>>Cyprus (CY)</option>
<option value="cz" <?php if($CurrentSetting == "cz") print " selected "; ?>>Czech Republic (CZ)</option>
<option value="dk" <?php if($CurrentSetting == "dk") print " selected "; ?>>Denmark (DK)</option>
<option value="dj" <?php if($CurrentSetting == "dj") print " selected "; ?>>Djibouti (DJ)</option>
<option value="dm" <?php if($CurrentSetting == "dm") print " selected "; ?>>Dominica (DM)</option>
<option value="do" <?php if($CurrentSetting == "do") print " selected "; ?>>Dominican Republic (DO)</option>
<option value="ec" <?php if($CurrentSetting == "ec") print " selected "; ?>>Ecuador (EC)</option>
<option value="eg" <?php if($CurrentSetting == "eg") print " selected "; ?>>Egypt (EG)</option>
<option value="sv" <?php if($CurrentSetting == "sv") print " selected "; ?>>El Salvador (SV)</option>
<option value="gq" <?php if($CurrentSetting == "gq") print " selected "; ?>>Equatorial Guinea (GQ)</option>
<option value="er" <?php if($CurrentSetting == "er") print " selected "; ?>>Eritrea (ER)</option>
<option value="ee" <?php if($CurrentSetting == "ee") print " selected "; ?>>Estonia (EE)</option>
<option value="et" <?php if($CurrentSetting == "et") print " selected "; ?>>Ethiopia (ET)</option>
<option value="fk" <?php if($CurrentSetting == "fk") print " selected "; ?>>Falkland Islands (malvinas) (FK)</option>
<option value="fo" <?php if($CurrentSetting == "fo") print " selected "; ?>>Faroe Islands (FO)</option>
<option value="fj" <?php if($CurrentSetting == "fj") print " selected "; ?>>Fiji (FJ)</option>
<option value="fi" <?php if($CurrentSetting == "fi") print " selected "; ?>>Finland (FI)</option>
<option value="fr" <?php if($CurrentSetting == "fr") print " selected "; ?>>France (FR)</option>
<option value="gf" <?php if($CurrentSetting == "gf") print " selected "; ?>>French Guiana (GF)</option>
<option value="pf" <?php if($CurrentSetting == "pf") print " selected "; ?>>French Polynesia (PF)</option>
<option value="tf" <?php if($CurrentSetting == "tf") print " selected "; ?>>French Southern Territories (TF)</option>
<option value="ga" <?php if($CurrentSetting == "ga") print " selected "; ?>>Gabon (GA)</option>
<option value="gm" <?php if($CurrentSetting == "gm") print " selected "; ?>>Gambia (GM)</option>
<option value="ge" <?php if($CurrentSetting == "ge") print " selected "; ?>>Georgia (GE)</option>
<option value="de" <?php if($CurrentSetting == "de") print " selected "; ?>>Germany (DE)</option>
<option value="gh" <?php if($CurrentSetting == "gh") print " selected "; ?>>Ghana (GH)</option>
<option value="gi" <?php if($CurrentSetting == "gi") print " selected "; ?>>Gibraltar (GI)</option>
<option value="gr" <?php if($CurrentSetting == "gr") print " selected "; ?>>Greece (GR)</option>
<option value="gl" <?php if($CurrentSetting == "gl") print " selected "; ?>>Greenland (GL)</option>
<option value="gd" <?php if($CurrentSetting == "gd") print " selected "; ?>>Grenada (GD)</option>
<option value="gp" <?php if($CurrentSetting == "gp") print " selected "; ?>>Guadeloupe (GP)</option>
<option value="gu" <?php if($CurrentSetting == "gu") print " selected "; ?>>Guam (GU)</option>
<option value="gt" <?php if($CurrentSetting == "gt") print " selected "; ?>>Guatemala (GT)</option>
<option value="gg" <?php if($CurrentSetting == "gg") print " selected "; ?>>Guernsey (GG)</option>
<option value="gn" <?php if($CurrentSetting == "gn") print " selected "; ?>>Guinea (GN)</option>
<option value="gw" <?php if($CurrentSetting == "gw") print " selected "; ?>>Guinea-bissau (GW)</option>
<option value="gy" <?php if($CurrentSetting == "gy") print " selected "; ?>>Guyana (GY)</option>
<option value="ht" <?php if($CurrentSetting == "ht") print " selected "; ?>>Haiti (HT)</option>
<option value="hm" <?php if($CurrentSetting == "hm") print " selected "; ?>>Heard Island And Mcdonald Islands (HM)</option>
<option value="va" <?php if($CurrentSetting == "va") print " selected "; ?>>Holy See (vatican City State) (VA)</option>
<option value="hn" <?php if($CurrentSetting == "hn") print " selected "; ?>>Honduras (HN)</option>
<option value="hk" <?php if($CurrentSetting == "hk") print " selected "; ?>>Hong Kong (HK)</option>
<option value="hu" <?php if($CurrentSetting == "hu") print " selected "; ?>>Hungary (HU)</option>
<option value="is" <?php if($CurrentSetting == "is") print " selected "; ?>>Iceland (IS)</option>
<option value="in" <?php if($CurrentSetting == "in") print " selected "; ?>>India (IN)</option>
<option value="id" <?php if($CurrentSetting == "id") print " selected "; ?>>Indonesia (ID)</option>
<option value="ir" <?php if($CurrentSetting == "ir") print " selected "; ?>>Iran, Islamic Republic Of (IR)</option>
<option value="iq" <?php if($CurrentSetting == "iq") print " selected "; ?>>Iraq (IQ)</option>
<option value="ie" <?php if($CurrentSetting == "ie") print " selected "; ?>>Ireland (IE)</option>
<option value="im" <?php if($CurrentSetting == "im") print " selected "; ?>>Isle Of Man (IM)</option>
<option value="il" <?php if($CurrentSetting == "il") print " selected "; ?>>Israel (IL)</option>
<option value="it" <?php if($CurrentSetting == "it") print " selected "; ?>>Italy (IT)</option>
<option value="jm" <?php if($CurrentSetting == "jm") print " selected "; ?>>Jamaica (JM)</option>
<option value="jp" <?php if($CurrentSetting == "jp") print " selected "; ?>>Japan (JP)</option>
<option value="je" <?php if($CurrentSetting == "je") print " selected "; ?>>Jersey (JE)</option>
<option value="jo" <?php if($CurrentSetting == "jo") print " selected "; ?>>Jordan (JO)</option>
<option value="kz" <?php if($CurrentSetting == "kz") print " selected "; ?>>Kazakhstan (KZ)</option>
<option value="ke" <?php if($CurrentSetting == "ke") print " selected "; ?>>Kenya (KE)</option>
<option value="ki" <?php if($CurrentSetting == "ki") print " selected "; ?>>Kiribati (KI)</option>
<option value="kp" <?php if($CurrentSetting == "kp") print " selected "; ?>>Korea, Democratic People's Republic Of (KP)</option>
<option value="kr" <?php if($CurrentSetting == "kr") print " selected "; ?>>Korea, Republic Of (KR)</option>
<option value="kw" <?php if($CurrentSetting == "kw") print " selected "; ?>>Kuwait (KW)</option>
<option value="kg" <?php if($CurrentSetting == "kg") print " selected "; ?>>Kyrgyzstan (KG)</option>
<option value="la" <?php if($CurrentSetting == "la") print " selected "; ?>>Lao People's Democratic Republic (LA)</option>
<option value="lv" <?php if($CurrentSetting == "lv") print " selected "; ?>>Latvia (LV)</option>
<option value="lb" <?php if($CurrentSetting == "lb") print " selected "; ?>>Lebanon (LB)</option>
<option value="ls" <?php if($CurrentSetting == "ls") print " selected "; ?>>Lesotho (LS)</option>
<option value="lr" <?php if($CurrentSetting == "lr") print " selected "; ?>>Liberia (LR)</option>
<option value="ly" <?php if($CurrentSetting == "ly") print " selected "; ?>>Libya (LY)</option>
<option value="li" <?php if($CurrentSetting == "li") print " selected "; ?>>Liechtenstein (LI)</option>
<option value="lt" <?php if($CurrentSetting == "lt") print " selected "; ?>>Lithuania (LT)</option>
<option value="lu" <?php if($CurrentSetting == "lu") print " selected "; ?>>Luxembourg (LU)</option>
<option value="mo" <?php if($CurrentSetting == "mo") print " selected "; ?>>Macao (MO)</option>
<option value="mk" <?php if($CurrentSetting == "mk") print " selected "; ?>>Macedonia, The Former Yugoslav Republic Of (MK)</option>
<option value="mg" <?php if($CurrentSetting == "mg") print " selected "; ?>>Madagascar (MG)</option>
<option value="mw" <?php if($CurrentSetting == "mw") print " selected "; ?>>Malawi (MW)</option>
<option value="my" <?php if($CurrentSetting == "my") print " selected "; ?>>Malaysia (MY)</option>
<option value="mv" <?php if($CurrentSetting == "mv") print " selected "; ?>>Maldives (MV)</option>
<option value="ml" <?php if($CurrentSetting == "ml") print " selected "; ?>>Mali (ML)</option>
<option value="mt" <?php if($CurrentSetting == "mt") print " selected "; ?>>Malta (MT)</option>
<option value="mh" <?php if($CurrentSetting == "mh") print " selected "; ?>>Marshall Islands (MH)</option>
<option value="mq" <?php if($CurrentSetting == "mq") print " selected "; ?>>Martinique (MQ)</option>
<option value="mr" <?php if($CurrentSetting == "mr") print " selected "; ?>>Mauritania (MR)</option>
<option value="mu" <?php if($CurrentSetting == "mu") print " selected "; ?>>Mauritius (MU)</option>
<option value="yt" <?php if($CurrentSetting == "yt") print " selected "; ?>>Mayotte (YT)</option>
<option value="mx" <?php if($CurrentSetting == "mx") print " selected "; ?>>Mexico (MX)</option>
<option value="fm" <?php if($CurrentSetting == "fm") print " selected "; ?>>Micronesia, Federated States Of (FM)</option>
<option value="md" <?php if($CurrentSetting == "md") print " selected "; ?>>Moldova, Republic Of (MD)</option>
<option value="mc" <?php if($CurrentSetting == "mc") print " selected "; ?>>Monaco (MC)</option>
<option value="mn" <?php if($CurrentSetting == "mn") print " selected "; ?>>Mongolia (MN)</option>
<option value="me" <?php if($CurrentSetting == "me") print " selected "; ?>>Montenegro (ME)</option>
<option value="ms" <?php if($CurrentSetting == "ms") print " selected "; ?>>Montserrat (MS)</option>
<option value="ma" <?php if($CurrentSetting == "ma") print " selected "; ?>>Morocco (MA)</option>
<option value="mz" <?php if($CurrentSetting == "mz") print " selected "; ?>>Mozambique (MZ)</option>
<option value="mm" <?php if($CurrentSetting == "mm") print " selected "; ?>>Myanmar (MM)</option>
<option value="na" <?php if($CurrentSetting == "na") print " selected "; ?>>Namibia (NA)</option>
<option value="nr" <?php if($CurrentSetting == "nr") print " selected "; ?>>Nauru (NR)</option>
<option value="np" <?php if($CurrentSetting == "np") print " selected "; ?>>Nepal (NP)</option>
<option value="nl" <?php if($CurrentSetting == "nl") print " selected "; ?>>Netherlands (NL)</option>
<option value="nc" <?php if($CurrentSetting == "nc") print " selected "; ?>>New Caledonia (NC)</option>
<option value="nz" <?php if($CurrentSetting == "nz") print " selected "; ?>>New Zealand (NZ)</option>
<option value="ni" <?php if($CurrentSetting == "ni") print " selected "; ?>>Nicaragua (NI)</option>
<option value="ne" <?php if($CurrentSetting == "ne") print " selected "; ?>>Niger (NE)</option>
<option value="ng" <?php if($CurrentSetting == "ng") print " selected "; ?>>Nigeria (NG)</option>
<option value="nu" <?php if($CurrentSetting == "nu") print " selected "; ?>>Niue (NU)</option>
<option value="nf" <?php if($CurrentSetting == "nf") print " selected "; ?>>Norfolk Island (NF)</option>
<option value="mp" <?php if($CurrentSetting == "mp") print " selected "; ?>>Northern Mariana Islands (MP)</option>
<option value="no" <?php if($CurrentSetting == "no") print " selected "; ?>>Norway (NO)</option>
<option value="om" <?php if($CurrentSetting == "om") print " selected "; ?>>Oman (OM)</option>
<option value="pk" <?php if($CurrentSetting == "pk") print " selected "; ?>>Pakistan (PK)</option>
<option value="pw" <?php if($CurrentSetting == "pw") print " selected "; ?>>Palau (PW)</option>
<option value="ps" <?php if($CurrentSetting == "ps") print " selected "; ?>>Palestine, State Of (PS)</option>
<option value="pa" <?php if($CurrentSetting == "pa") print " selected "; ?>>Panama (PA)</option>
<option value="pg" <?php if($CurrentSetting == "pg") print " selected "; ?>>Papua New Guinea (PG)</option>
<option value="py" <?php if($CurrentSetting == "py") print " selected "; ?>>Paraguay (PY)</option>
<option value="pe" <?php if($CurrentSetting == "pe") print " selected "; ?>>Peru (PE)</option>
<option value="ph" <?php if($CurrentSetting == "ph") print " selected "; ?>>Philippines (PH)</option>
<option value="pn" <?php if($CurrentSetting == "pn") print " selected "; ?>>Pitcairn (PN)</option>
<option value="pl" <?php if($CurrentSetting == "pl") print " selected "; ?>>Poland (PL)</option>
<option value="pt" <?php if($CurrentSetting == "pt") print " selected "; ?>>Portugal (PT)</option>
<option value="pr" <?php if($CurrentSetting == "pr") print " selected "; ?>>Puerto Rico (PR)</option>
<option value="qa" <?php if($CurrentSetting == "qa") print " selected "; ?>>Qatar (QA)</option>
<option value="re" <?php if($CurrentSetting == "re") print " selected "; ?>>Réunion (RE)</option>
<option value="ro" <?php if($CurrentSetting == "ro") print " selected "; ?>>Romania (RO)</option>
<option value="ru" <?php if($CurrentSetting == "ru") print " selected "; ?>>Russian Federation (RU)</option>
<option value="rw" <?php if($CurrentSetting == "rw") print " selected "; ?>>Rwanda (RW)</option>
<option value="bl" <?php if($CurrentSetting == "bl") print " selected "; ?>>Saint Barthélemy (BL)</option>
<option value="sh" <?php if($CurrentSetting == "sh") print " selected "; ?>>Saint Helena, Ascension And Tristan Da Cunha (SH)</option>
<option value="kn" <?php if($CurrentSetting == "kn") print " selected "; ?>>Saint Kitts And Nevis (KN)</option>
<option value="lc" <?php if($CurrentSetting == "lc") print " selected "; ?>>Saint Lucia (LC)</option>
<option value="mf" <?php if($CurrentSetting == "mf") print " selected "; ?>>Saint Martin (french Part) (MF)</option>
<option value="pm" <?php if($CurrentSetting == "pm") print " selected "; ?>>Saint Pierre And Miquelon (PM)</option>
<option value="vc" <?php if($CurrentSetting == "vc") print " selected "; ?>>Saint Vincent And The Grenadines (VC)</option>
<option value="ws" <?php if($CurrentSetting == "ws") print " selected "; ?>>Samoa (WS)</option>
<option value="sm" <?php if($CurrentSetting == "sm") print " selected "; ?>>San Marino (SM)</option>
<option value="st" <?php if($CurrentSetting == "st") print " selected "; ?>>Sao Tome And Principe (ST)</option>
<option value="sa" <?php if($CurrentSetting == "sa") print " selected "; ?>>Saudi Arabia (SA)</option>
<option value="sn" <?php if($CurrentSetting == "sn") print " selected "; ?>>Senegal (SN)</option>
<option value="rs" <?php if($CurrentSetting == "rs") print " selected "; ?>>Serbia (RS)</option>
<option value="sc" <?php if($CurrentSetting == "sc") print " selected "; ?>>Seychelles (SC)</option>
<option value="sl" <?php if($CurrentSetting == "sl") print " selected "; ?>>Sierra Leone (SL)</option>
<option value="sg" <?php if($CurrentSetting == "sg") print " selected "; ?>>Singapore (SG)</option>
<option value="sx" <?php if($CurrentSetting == "sx") print " selected "; ?>>Sint Maarten (dutch Part) (SX)</option>
<option value="sk" <?php if($CurrentSetting == "sk") print " selected "; ?>>Slovakia (SK)</option>
<option value="si" <?php if($CurrentSetting == "si") print " selected "; ?>>Slovenia (SI)</option>
<option value="sb" <?php if($CurrentSetting == "sb") print " selected "; ?>>Solomon Islands (SB)</option>
<option value="so" <?php if($CurrentSetting == "so") print " selected "; ?>>Somalia (SO)</option>
<option value="za" <?php if($CurrentSetting == "za") print " selected "; ?>>South Africa (ZA)</option>
<option value="gs" <?php if($CurrentSetting == "gs") print " selected "; ?>>South Georgia And The South Sandwich Islands (GS)</option>
<option value="ss" <?php if($CurrentSetting == "ss") print " selected "; ?>>South Sudan (SS)</option>
<option value="es" <?php if($CurrentSetting == "es") print " selected "; ?>>Spain (ES)</option>
<option value="lk" <?php if($CurrentSetting == "lk") print " selected "; ?>>Sri Lanka (LK)</option>
<option value="sd" <?php if($CurrentSetting == "sd") print " selected "; ?>>Sudan (SD)</option>
<option value="sr" <?php if($CurrentSetting == "sr") print " selected "; ?>>Suriname (SR)</option>
<option value="sj" <?php if($CurrentSetting == "sj") print " selected "; ?>>Svalbard And Jan Mayen (SJ)</option>
<option value="sz" <?php if($CurrentSetting == "sz") print " selected "; ?>>Swaziland (SZ)</option>
<option value="se" <?php if($CurrentSetting == "se") print " selected "; ?>>Sweden (SE)</option>
<option value="ch" <?php if($CurrentSetting == "ch") print " selected "; ?>>Switzerland (CH)</option>
<option value="sy" <?php if($CurrentSetting == "sy") print " selected "; ?>>Syrian Arab Republic (SY)</option>
<option value="tw" <?php if($CurrentSetting == "tw") print " selected "; ?>>Taiwan, Province Of China (TW)</option>
<option value="tj" <?php if($CurrentSetting == "tj") print " selected "; ?>>Tajikistan (TJ)</option>
<option value="tz" <?php if($CurrentSetting == "tz") print " selected "; ?>>Tanzania, United Republic Of (TZ)</option>
<option value="th" <?php if($CurrentSetting == "th") print " selected "; ?>>Thailand (TH)</option>
<option value="tl" <?php if($CurrentSetting == "tl") print " selected "; ?>>Timor-leste (TL)</option>
<option value="tg" <?php if($CurrentSetting == "tg") print " selected "; ?>>Togo (TG)</option>
<option value="tk" <?php if($CurrentSetting == "tk") print " selected "; ?>>Tokelau (TK)</option>
<option value="to" <?php if($CurrentSetting == "to") print " selected "; ?>>Tonga (TO)</option>
<option value="tt" <?php if($CurrentSetting == "tt") print " selected "; ?>>Trinidad And Tobago (TT)</option>
<option value="tn" <?php if($CurrentSetting == "tn") print " selected "; ?>>Tunisia (TN)</option>
<option value="tr" <?php if($CurrentSetting == "tr") print " selected "; ?>>Turkey (TR)</option>
<option value="tm" <?php if($CurrentSetting == "tm") print " selected "; ?>>Turkmenistan (TM)</option>
<option value="tc" <?php if($CurrentSetting == "tc") print " selected "; ?>>Turks And Caicos Islands (TC)</option>
<option value="tv" <?php if($CurrentSetting == "tv") print " selected "; ?>>Tuvalu (TV)</option>
<option value="ug" <?php if($CurrentSetting == "ug") print " selected "; ?>>Uganda (UG)</option>
<option value="ua" <?php if($CurrentSetting == "ua") print " selected "; ?>>Ukraine (UA)</option>
<option value="ae" <?php if($CurrentSetting == "ae") print " selected "; ?>>United Arab Emirates (AE)</option>
<option value="gb" <?php if($CurrentSetting == "gb") print " selected "; ?>>United Kingdom (GB)</option>
<option value="us" <?php if($CurrentSetting == "us") print " selected "; ?>>United States (US)</option>
<option value="um" <?php if($CurrentSetting == "um") print " selected "; ?>>United States Minor Outlying Islands (UM)</option>
<option value="uy" <?php if($CurrentSetting == "uy") print " selected "; ?>>Uruguay (UY)</option>
<option value="uz" <?php if($CurrentSetting == "uz") print " selected "; ?>>Uzbekistan (UZ)</option>
<option value="vu" <?php if($CurrentSetting == "vu") print " selected "; ?>>Vanuatu (VU)</option>
<option value="ve" <?php if($CurrentSetting == "ve") print " selected "; ?>>Venezuela, Bolivarian Republic Of (VE)</option>
<option value="vn" <?php if($CurrentSetting == "vn") print " selected "; ?>>Viet Nam (VN)</option>
<option value="vg" <?php if($CurrentSetting == "vg") print " selected "; ?>>Virgin Islands, British (VG)</option>
<option value="vi" <?php if($CurrentSetting == "vi") print " selected "; ?>>Virgin Islands, U.s. (VI)</option>
<option value="wf" <?php if($CurrentSetting == "wf") print " selected "; ?>>Wallis And Futuna (WF)</option>
<option value="eh" <?php if($CurrentSetting == "eh") print " selected "; ?>>Western Sahara (EH)</option>
<option value="ye" <?php if($CurrentSetting == "ye") print " selected "; ?>>Yemen (YE)</option>
<option value="zm" <?php if($CurrentSetting == "zm") print " selected "; ?>>Zambia (ZM)</option>
<option value="zw" <?php if($CurrentSetting == "zw") print " selected "; ?>>Zimbabwe (ZW)</option>
